- model: ks
  operations:
    train:
      sourcecode:
        - exclude: '*.ipynb'
        - exclude: '*.md'
        - exclude: '.git*'
      requires:
        - file: data/ks/ks_tr8_xr64_en1.npy
          target-path: data/ks
          target-type: link
        - file: figs
          target-type: link
      main: src.fusion1d
      output-scalars:
        - step: 'epoch: (\step)'
        - train_loss: 'train_loss: (\value)'
        - loss: 'valid_loss: (\value)'
      flags:
        datafile: 'ks_tr8_xr64_en1.npy'
        DEVRUN: False
        MAKEFIGS: True
        MAKEVIDS: True
        valid_n: 2000
        epochs: 80
        bs: 128
        lr: 0.001
        l1: 8192
        l2: 64
        d1: 0.3
        d2: 0.0


- model: sh_sh
  operations:
    train:
      sourcecode:
        - exclude: '*.ipynb'
        - exclude: '*.md'
        - exclude: '.git*'
      requires:
        - file: data/ael/sh_sh_exp0_tr8_xr3_yr3_en1.npy
          target-path: data/ael
          target-type: link
        - file: figs
          target-type: link
      main: src.fusion2d
      output-scalars:
        - step: 'epoch: (\step)'
        - train_loss: 'train_loss: (\value)'
        - loss: 'valid_loss: (\value)'
      flags:
        datafile: 'sh_sh_exp0_tr8_xr3_yr3_en1.npy'
        DEVRUN: False
        MAKEFIGS: True
        MAKEVIDS: True
        valid_n: 500
        epochs: 500
        bs: 64
        lr: 0.0025
        l1: 8192
        l2: 256
        d1: 0.3
        d2: 0.0


- model: dh_dh
  operations:
    train:
      sourcecode:
        - exclude: '*.ipynb'
        - exclude: '*.md'
        - exclude: '.git*'
      requires:
        - file: data/ael/dh_dh_exp0_tr8_xr3_yr3_en1.npy
          target-path: data/ael
          target-type: link
        - file: data/ael/dh_dh_exp0_tr8_xr3_yr3_en2.npy
          target-path: data/ael
          target-type: link
        - file: data/ael/dh_dh_exp0_tr8_xr10_yr10_en1.npy
          target-path: data/ael
          target-type: link
        - file: data/ael/dh_dh_exp0_tr5_xr5_yr5_en1.npy
          target-path: data/ael
          target-type: link
        - file: figs
          target-type: link
      main: src.fusion2d
      output-scalars:
        - step: 'epoch: (\step)'
        - train_loss: 'train_loss: (\value)'
        - loss: 'valid_loss: (\value)'
      flags:
        datafile: 'dh_dh_exp0_tr8_xr3_yr3_en1.npy'
        DEVRUN: False
        MAKEFIGS: True
        MAKEVIDS: True
        valid_n: 500
        epochs: 3000
        bs: 512
        lr: 1e-4
        l1: 2759
        l2: 296
        d1: 0.3
        d2: 0.0


- model: sh_dh
  operations:
    train:
      sourcecode:
        - exclude: '*.ipynb'
        - exclude: '*.md'
        - exclude: '.git*'
      requires:
        - file: data/ael/sh_dh_exp0_en1.npy
          target-path: data/ael
          target-type: link
        - file: data/ael/sh_dh_exp0_en2.npy
          target-path: data/ael
          target-type: link
        - file: figs
          target-type: link
      main: src.fusion2d
      output-scalars:
        - step: 'epoch: (\step)'
        - train_loss: 'train_loss: (\value)'
        - loss: 'valid_loss: (\value)'
      flags:
        datafile: 'sh_dh_exp0_en1.npy'
        DEVRUN: False
        MAKEFIGS: True
        MAKEVIDS: True
        valid_n: 500
        epochs: 5000
        bs: 64
        lr: 0.03
        l1: 8192
        l2: 512
        d1: 0.3
        d2: 0.0